version: 0.1
phases:
  install:
    runtime-versions:
        python: 3.8

  install:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - pipenv run sam package --template-file template.yaml --s3-bucket my-code-pipeline-cdci --output-template-file outputSamTemplate.yaml
      
artifacts:
  files:
    - template.yaml
    - outputSamTemplate.yaml