version: 0.1
phases:
  install:
    commands:
      - sam build -t template.yaml
      - aws cloudformation package --template-file template.yaml --s3-bucket my-code-pipeline-cdci --output-template-file outputSamTemplate.yaml
      
artifacts:
  files:
    - template.yaml
    - outputSamTemplate.yaml