version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - pipenv run sam package --s3-bucket my-code-pipeline-cdci --output-template-file outputSamTemplate.yaml
      
artifacts:
  files:
    - outputSamTemplate.yaml